// Generated by AI on 03/13/2026
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { RouterProvider } from 'react-router-dom';
import { EnvironmentProvider } from '../shared/environment/EnvironmentContext';
import { router } from './router';

const queryClient = new QueryClient();

export default function App() {
  return (
    <EnvironmentProvider>
      <QueryClientProvider client={queryClient}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    </EnvironmentProvider>
  );
}
