// Generated by AI on 03/13/2026
import { useState } from 'react';
import { Outlet, NavLink } from 'react-router-dom';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Drawer from '@mui/material/Drawer';
import InputLabel from '@mui/material/InputLabel';
import FormControl from '@mui/material/FormControl';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemText from '@mui/material/ListItemText';
import MenuItem from '@mui/material/MenuItem';
import Select from '@mui/material/Select';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import type { AppEnvironment } from '../shared/environment/EnvironmentContext';
import { useEnvironment } from '../shared/environment/EnvironmentContext';

const DRAWER_WIDTH = 240;

const ENV_COLORS: Record<AppEnvironment, string> = {
  QSB: '#2e7d32',
  STAGING: '#e65100',
  PROD: '#c62828',
};

const navItems = [
  { label: 'Dashboard', to: '/', group: null },
  { label: 'CTR Monitoring', to: null, group: 'ctr-monitoring' },
  { label: 'Failed CTRs', to: '/ctr-monitoring/failed', group: 'ctr-monitoring' },
  { label: 'For Regeneration', to: '/ctr-monitoring/regeneration', group: 'ctr-monitoring' },
  { label: 'Requires Attention', to: '/ctr-monitoring/attention', group: 'ctr-monitoring' },
  { label: 'CTR Management', to: null, group: 'ctr-management' },
  { label: 'Generate Form', to: '/ctr-management/generate-form', group: 'ctr-management' },
  { label: 'Regenerate CTR', to: '/ctr-management/regenerate-ctr', group: 'ctr-management' },
  { label: 'Paychex', to: null, group: 'paychex' },
  { label: 'Client Status', to: '/paychex/status', group: 'paychex' },
] as const;

export default function AppShell() {
  const { environment, setEnvironment } = useEnvironment();
  const [_open, _setOpen] = useState(true);

  const handleEnvChange = (event: { target: { value: string } }) => {
    setEnvironment(event.target.value as AppEnvironment);
  };

  const sidebar = (
    <Box sx={{ overflow: 'auto' }}>
      <List disablePadding>
        {navItems.map((item) => {
          // Group headers — not clickable
          if (item.to === null) {
            return (
              <ListItem key={item.label} disablePadding>
                <ListItemText
                  primary={item.label}
                  sx={{ px: 2, pt: 2, pb: 0.5, color: 'text.secondary', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.7rem' }}
                  primaryTypographyProps={{ variant: 'caption', fontWeight: 700, textTransform: 'uppercase', color: 'text.secondary' }}
                />
              </ListItem>
            );
          }

          // Nav links
          return (
            <NavLink
              key={item.to}
              to={item.to}
              end={item.to === '/'}
              style={{ textDecoration: 'none', color: 'inherit' }}
            >
              {({ isActive }) => (
                <ListItemButton
                  selected={isActive}
                  sx={{ pl: item.group !== null ? 3 : 2 }}
                >
                  <ListItemText primary={item.label} />
                </ListItemButton>
              )}
            </NavLink>
          );
        })}
      </List>
    </Box>
  );

  return (
    <Box sx={{ display: 'flex' }}>
      <AppBar position="fixed" sx={{ zIndex: (theme: { zIndex: { drawer: number } }) => theme.zIndex.drawer + 1 }}>
        <Toolbar>
          <Typography variant="h6" noWrap component="div" sx={{ flexGrow: 1 }}>
            QuarterEnd Tax Support Utils
          </Typography>
          <FormControl size="small" variant="outlined" sx={{ minWidth: 120 }}>
            <InputLabel sx={{ color: 'white' }}>Environment</InputLabel>
            <Select
              value={environment}
              label="Environment"
              onChange={handleEnvChange}
              sx={{
                color: 'white',
                borderColor: 'white',
                '& .MuiOutlinedInput-notchedOutline': { borderColor: 'rgba(255,255,255,0.5)' },
                '& .MuiSvgIcon-root': { color: 'white' },
                backgroundColor: ENV_COLORS[environment],
              }}
            >
              <MenuItem value="QSB">QSB</MenuItem>
              <MenuItem value="STAGING">STAGING</MenuItem>
              <MenuItem value="PROD">PROD</MenuItem>
            </Select>
          </FormControl>
        </Toolbar>
      </AppBar>

      <Drawer
        variant="permanent"
        sx={{
          width: DRAWER_WIDTH,
          flexShrink: 0,
          '& .MuiDrawer-paper': { width: DRAWER_WIDTH, boxSizing: 'border-box' },
        }}
      >
        <Toolbar />
        {sidebar}
      </Drawer>

      <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
        <Toolbar />
        <Outlet />
      </Box>
    </Box>
  );
}
