// Generated by AI on 03/13/2026
import { createBrowserRouter } from 'react-router-dom';
import AppShell from './AppShell';
import DashboardPage from '../features/dashboard/DashboardPage';
import FailedCtrsPage from '../features/ctr-monitoring/FailedCtrsPage';
import CtrsForRegenerationPage from '../features/ctr-monitoring/CtrsForRegenerationPage';
import CtrsAttentionPage from '../features/ctr-monitoring/CtrsAttentionPage';
import GenerateFormPage from '../features/ctr-management/GenerateFormPage';
import RegenerateCtrPage from '../features/ctr-management/RegenerateCtrPage';
import PaychexClientStatusPage from '../features/paychex/PaychexClientStatusPage';

export const router = createBrowserRouter([
  {
    path: '/',
    element: <AppShell />,
    children: [
      { index: true, element: <DashboardPage /> },
      { path: 'ctr-monitoring/failed', element: <FailedCtrsPage /> },
      { path: 'ctr-monitoring/regeneration', element: <CtrsForRegenerationPage /> },
      { path: 'ctr-monitoring/attention', element: <CtrsAttentionPage /> },
      { path: 'ctr-management/generate-form', element: <GenerateFormPage /> },
      { path: 'ctr-management/regenerate-ctr', element: <RegenerateCtrPage /> },
      { path: 'paychex/status', element: <PaychexClientStatusPage /> },
    ],
  },
]);
