// Generated by AI on 03/13/2026
using System.Data;
using AITrail.QuarterEndTaxSupportUtils.Business.Common.Environment;
using Microsoft.Data.SqlClient;

namespace AITrail.QuarterEndTaxSupportUtils.Business.Common.Infrastructure;

public class SqlConnectionFactory
{
    private readonly EnvironmentConnectionResolver _resolver;

    public SqlConnectionFactory(EnvironmentConnectionResolver resolver)
    {
        _resolver = resolver;
    }

    public IDbConnection CreateConnection(AppEnvironment env)
    {
        var connectionString = _resolver.GetConnectionString(env);
        return new SqlConnection(connectionString);
    }
}
