// Generated by AI on 03/15/2026
using AITrail.QuarterEndTaxSupportUtils.Business.Common.Environment;
using Microsoft.Extensions.Configuration;

namespace AITrail.QuarterEndTaxSupportUtils.Business.Common.Infrastructure;

public class TaxSnapshotConnectionStringProvider
{
    private readonly IConfiguration _configuration;

    public TaxSnapshotConnectionStringProvider(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public string GetTaxSnapshotDbConnectionString(AppEnvironment env)
    {
        var key = env switch
        {
            AppEnvironment.QSB => "TaxSnapshotDbConnectionString_QSB",
            AppEnvironment.Staging => "TaxSnapshotDbConnectionString_RC",
            AppEnvironment.Prod => "TaxSnapshotDbConnectionString_PROD",
            _ => throw new NotSupportedException($"AppEnvironment '{env}' is not supported.")
        };

        return _configuration.GetConnectionString(key)
            ?? throw new InvalidOperationException($"Connection string '{key}' is not configured.");
    }
}
