// Generated by AI on 03/13/2026
import axios from 'axios';
import { getEnvironment } from '../environment/EnvironmentContext';

export const axiosClient = axios.create({
  baseURL: '/api/v1',
});

axiosClient.interceptors.request.use((config) => {
  config.params = { ...config.params, environment: getEnvironment() };
  return config;
});
