// Generated by AI on 03/15/2026
import { axiosClient } from '../../shared/api/axiosClient';
import type { FailedCtr, FailedForm } from './types';

export async function fetchFailedCtrs(from: string, to: string): Promise<FailedCtr[]> {
  const response = await axiosClient.get<FailedCtr[]>('/ctr-monitoring/failed', {
    params: { from, to },
  });
  return response.data;
}

export async function fetchFailedFormsForCtr(taxPacketGuid: string): Promise<FailedForm[]> {
  const response = await axiosClient.get<FailedForm[]>(
    `/ctr-monitoring/failed/${taxPacketGuid}/forms`
  );
  return response.data;
}
