// Generated by AI on 03/15/2026
using AITrail.QuarterEndTaxSupportUtils.Business.Features.FailedCtrs;

namespace AITrail.QuarterEndTaxSupportUtils.Tests.Features.FailedCtrs;

public class FailedCtrServiceTests
{
    // Tests for IsTransientError (internal static helper)

    [Theory]
    [InlineData("Failed to upload generated file to PRS API", null, true)]
    [InlineData(null, "Failed to upload generated file to PRS API", true)]
    [InlineData("Execution Timeout Expired", null, true)]
    [InlineData(null, "Execution Timeout Expired", true)]
    [InlineData("Microsoft.Data.SqlClient.SqlException", null, true)]
    [InlineData(null, "Microsoft.Data.SqlClient.SqlException", true)]
    [InlineData("The wait operation timed out", null, true)]
    [InlineData(null, "The wait operation timed out", true)]
    [InlineData("This SqlTransaction has completed; it is no longer usable", null, true)]
    [InlineData(null, "This SqlTransaction has completed; it is no longer usable", true)]
    [InlineData("Some message with Execution Timeout Expired inside", null, true)]
    [InlineData(null, "prefix Microsoft.Data.SqlClient.SqlException suffix", true)]
    public void IsTransientError_ReturnsTrue_WhenKeywordPresent(
        string? reportDataTransMessage,
        string? pdfGenMessage,
        bool expected)
    {
        var result = FailedCtrService.IsTransientError(reportDataTransMessage, pdfGenMessage);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("Success", "Success", false)]
    [InlineData(null, null, false)]
    [InlineData("", "", false)]
    [InlineData("UnexpectedFailure", "UnexpectedFailure", false)]
    [InlineData("Some random error message", "Another random message", false)]
    public void IsTransientError_ReturnsFalse_WhenNoKeywordPresent(
        string? reportDataTransMessage,
        string? pdfGenMessage,
        bool expected)
    {
        var result = FailedCtrService.IsTransientError(reportDataTransMessage, pdfGenMessage);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void IsTransientError_ReturnsFalse_WhenBothInputsNull()
    {
        var result = FailedCtrService.IsTransientError(null, null);
        Assert.False(result);
    }

    [Fact]
    public void IsTransientError_ReturnsTrue_WhenBothMessagesContainKeywords()
    {
        var result = FailedCtrService.IsTransientError(
            "Execution Timeout Expired",
            "Microsoft.Data.SqlClient.SqlException");
        Assert.True(result);
    }
}
