// Generated by AI on 03/13/2026
using System.Net;
using System.Text.Json;
using AITrail.QuarterEndTaxSupportUtils.Business.Common.Exceptions;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;

namespace AITrail.QuarterEndTaxSupportUtils.API.Middleware;

public class GlobalExceptionMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<GlobalExceptionMiddleware> _logger;

    public GlobalExceptionMiddleware(RequestDelegate next, ILogger<GlobalExceptionMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        try
        {
            await _next(context);
        }
        catch (ValidationException ex)
        {
            _logger.LogWarning(ex, "Validation failed for request {Method} {Path}", context.Request.Method, context.Request.Path);
            await WriteProblemDetailsAsync(context, HttpStatusCode.BadRequest, "Validation failed");
        }
        catch (NotFoundException ex)
        {
            _logger.LogWarning(ex, "Resource not found for request {Method} {Path}", context.Request.Method, context.Request.Path);
            await WriteProblemDetailsAsync(context, HttpStatusCode.NotFound, "Resource not found");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unhandled exception for request {Method} {Path}", context.Request.Method, context.Request.Path);
            await WriteProblemDetailsAsync(context, HttpStatusCode.InternalServerError, "An unexpected error occurred");
        }
    }

    private static async Task WriteProblemDetailsAsync(HttpContext context, HttpStatusCode statusCode, string title)
    {
        var problem = new ProblemDetails
        {
            Status = (int)statusCode,
            Title = title,
            Instance = context.Request.Path
        };

        context.Response.ContentType = "application/problem+json";
        context.Response.StatusCode = (int)statusCode;

        await context.Response.WriteAsync(JsonSerializer.Serialize(problem));
    }
}
