// Generated by AI on 03/13/2026
namespace AITrail.QuarterEndTaxSupportUtils.Business.Common.Exceptions;

public class NotFoundException : Exception
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
