// Generated by AI on 03/13/2026
namespace AITrail.QuarterEndTaxSupportUtils.API.Endpoints;

public static class HealthEndpoint
{
    public static void MapHealthEndpoints(this WebApplication app)
    {
        app.MapGet("/api/v1/health", () => Results.Ok(new { status = "ok" }))
            .WithName("GetHealth")
            .WithTags("Health");
    }
}
