// Generated by AI on 03/13/2026
using AITrail.QuarterEndTaxSupportUtils.Business.Common.Environment;
using Microsoft.Extensions.Configuration;

namespace AITrail.QuarterEndTaxSupportUtils.Business.Common.Environment;

public class EnvironmentConnectionResolver
{
    private readonly IConfiguration _configuration;

    public EnvironmentConnectionResolver(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public string GetConnectionString(AppEnvironment env)
    {
        return env switch
        {
            AppEnvironment.QSB => _configuration.GetConnectionString("QSB")
                ?? throw new InvalidOperationException("Connection string 'QSB' is not configured."),
            AppEnvironment.Staging => _configuration.GetConnectionString("Staging")
                ?? throw new InvalidOperationException("Connection string 'Staging' is not configured."),
            AppEnvironment.Prod => _configuration.GetConnectionString("Prod")
                ?? throw new InvalidOperationException("Connection string 'Prod' is not configured."),
            _ => throw new NotSupportedException($"AppEnvironment '{env}' is not supported.")
        };
    }

    public string GetDownstreamBaseUrl(AppEnvironment env)
    {
        return env switch
        {
            AppEnvironment.QSB => _configuration["DownstreamServices:QSB:BaseUrl"]
                ?? throw new InvalidOperationException("DownstreamServices:QSB:BaseUrl is not configured."),
            AppEnvironment.Staging => _configuration["DownstreamServices:Staging:BaseUrl"]
                ?? throw new InvalidOperationException("DownstreamServices:Staging:BaseUrl is not configured."),
            AppEnvironment.Prod => _configuration["DownstreamServices:Prod:BaseUrl"]
                ?? throw new InvalidOperationException("DownstreamServices:Prod:BaseUrl is not configured."),
            _ => throw new NotSupportedException($"AppEnvironment '{env}' is not supported.")
        };
    }
}
