// Generated by AI on 03/15/2026
namespace AITrail.QuarterEndTaxSupportUtils.Business.Features.FailedCtrs;

public record FailedTaxReportGenerationStatusQueryModel(
    TaxReportGenerationStatusQueryModel TaxReportGenerationStatus,
    bool IsFailedBecauseOfTransientError
);
