// Generated by AI on 03/15/2026
using AITrail.QuarterEndTaxSupportUtils.Business.Common.Environment;
using AITrail.QuarterEndTaxSupportUtils.Business.Common.Infrastructure;
using Dapper;
using Microsoft.Data.SqlClient;

namespace AITrail.QuarterEndTaxSupportUtils.Business.Features.FailedCtrs;

public class FailedCtrService : IFailedCtrService
{
    private readonly TaxSnapshotConnectionStringProvider _connectionStringProvider;

    private static readonly string[] TransientErrorKeywords =
    [
        "Failed to upload generated file to PRS API",
        "Execution Timeout Expired",
        "Microsoft.Data.SqlClient.SqlException",
        "The wait operation timed out",
        "This SqlTransaction has completed; it is no longer usable"
    ];

    private const string GetFailedCTRsQuery = """
        SELECT
            tpgps.TaxPacketGuid,
            tpgps.PQUID,
            tpgps.ClientId,
            tpgps.Year,
            tpgps.Quarter,
            tpgps.ProcessStatus,
            tpgps.Message,
            tpgps.META_DateCreated,
            tpgps.ReportType,
            tpgps.IsReportWizardCTR
        FROM TaxPacketGenerationProcessStatus tpgps
        WHERE tpgps.ProcessStatus = 'PROCESS_FAILED'
          AND tpgps.META_DateCreated >= @from
          AND tpgps.META_DateCreated <= @to;
        """;

    private const string GetFailedFormsForCTRQuery = """
        SELECT
            TaxPacketGuid,
            Id,
            ReportName,
            ReportStatus,
            ReportDataTransStatus,
            PdfGenStatus,
            ReportDataTransMessage,
            PdfGenMessage,
            TaxAuthCode,
            TaxCode,
            TaxFormName,
            GenerationType
        FROM TaxReportGenerationStatus
        WHERE TaxPacketGuid = @taxPacketGuid
          AND ReportStatus = 'F';
        """;

    public FailedCtrService(TaxSnapshotConnectionStringProvider connectionStringProvider)
    {
        _connectionStringProvider = connectionStringProvider;
    }

    public async Task<IReadOnlyList<TaxPacketGenerationProcessStatusQueryModel>> GetFailedCtrsAsync(
        AppEnvironment env,
        DateTimeOffset from,
        DateTimeOffset to)
    {
        var connectionString = _connectionStringProvider.GetTaxSnapshotDbConnectionString(env);
        await using var connection = new SqlConnection(connectionString);

        var results = await connection.QueryAsync<TaxPacketGenerationProcessStatusQueryModel>(
            GetFailedCTRsQuery,
            new { from, to });

        return results.ToList().AsReadOnly();
    }

    public async Task<IReadOnlyList<FailedTaxReportGenerationStatusQueryModel>> GetFailedFormsForCtrAsync(
        AppEnvironment env,
        Guid taxPacketGuid)
    {
        var connectionString = _connectionStringProvider.GetTaxSnapshotDbConnectionString(env);
        await using var connection = new SqlConnection(connectionString);

        var rows = await connection.QueryAsync<TaxReportGenerationStatusQueryModel>(
            GetFailedFormsForCTRQuery,
            new { taxPacketGuid });

        return rows
            .Select(row => new FailedTaxReportGenerationStatusQueryModel(
                TaxReportGenerationStatus: row,
                IsFailedBecauseOfTransientError: IsTransientError(row.ReportDataTransMessage, row.PdfGenMessage)))
            .ToList()
            .AsReadOnly();
    }

    internal static bool IsTransientError(string? reportDataTransMessage, string? pdfGenMessage)
    {
        foreach (var keyword in TransientErrorKeywords)
        {
            if ((reportDataTransMessage?.Contains(keyword, StringComparison.OrdinalIgnoreCase) ?? false)
                || (pdfGenMessage?.Contains(keyword, StringComparison.OrdinalIgnoreCase) ?? false))
            {
                return true;
            }
        }

        return false;
    }
}
