// Generated by AI on 03/15/2026
using AITrail.QuarterEndTaxSupportUtils.Business.Common.Environment;

namespace AITrail.QuarterEndTaxSupportUtils.Business.Features.FailedCtrs;

public interface IFailedCtrService
{
    Task<IReadOnlyList<TaxPacketGenerationProcessStatusQueryModel>> GetFailedCtrsAsync(
        AppEnvironment env,
        DateTimeOffset from,
        DateTimeOffset to);

    Task<IReadOnlyList<FailedTaxReportGenerationStatusQueryModel>> GetFailedFormsForCtrAsync(
        AppEnvironment env,
        Guid taxPacketGuid);
}
