// Generated by AI on 03/15/2026
namespace AITrail.QuarterEndTaxSupportUtils.Business.Features.FailedCtrs;

public record TaxPacketGenerationProcessStatusQueryModel(
    Guid TaxPacketGuid,
    long PQUID,
    int ClientId,
    int Year,
    int Quarter,
    string ProcessStatus,
    string Message,
    DateTimeOffset META_DateCreated,
    string ReportType,
    bool IsReportWizardCTR
);
