// Generated by AI on 03/15/2026
namespace AITrail.QuarterEndTaxSupportUtils.Business.Features.FailedCtrs;

public record TaxReportGenerationStatusQueryModel(
    Guid TaxPacketGuid,
    Guid Id,
    string ReportName,
    string ReportStatus,
    string ReportDataTransStatus,
    string PdfGenStatus,
    string ReportDataTransMessage,
    string PdfGenMessage,
    string TaxAuthCode,
    string TaxCode,
    string TaxFormName,
    string GenerationType
);
