// Generated by AI on 03/13/2026
import { createContext, useContext, useEffect, useRef, useState } from 'react';

export type AppEnvironment = 'QSB' | 'STAGING' | 'PROD';

interface EnvironmentContextValue {
  environment: AppEnvironment;
  setEnvironment: (env: AppEnvironment) => void;
}

export const EnvironmentContext = createContext<EnvironmentContextValue>({
  environment: 'QSB',
  setEnvironment: () => {},
});

// Module-level ref so axiosClient can read the current environment
// without violating rules of hooks (no hook calls outside React components)
let currentEnvironment: AppEnvironment = 'QSB';

export function getEnvironment(): AppEnvironment {
  return currentEnvironment;
}

export function EnvironmentProvider({ children }: { children: React.ReactNode }) {
  const [environment, setEnvironmentState] = useState<AppEnvironment>('QSB');
  const isFirstRender = useRef(true);

  useEffect(() => {
    currentEnvironment = environment;
  }, [environment]);

  // Sync on first render
  if (isFirstRender.current) {
    currentEnvironment = environment;
    isFirstRender.current = false;
  }

  const setEnvironment = (env: AppEnvironment) => {
    currentEnvironment = env;
    setEnvironmentState(env);
  };

  return (
    <EnvironmentContext.Provider value={{ environment, setEnvironment }}>
      {children}
    </EnvironmentContext.Provider>
  );
}

export function useEnvironment(): EnvironmentContextValue {
  return useContext(EnvironmentContext);
}
